# Generated by Django 4.1.1 on 2022-09-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AcctType', models.CharField(max_length=30, verbose_name='Account Type')),
                ('Account', models.CharField(max_length=10, unique=True, verbose_name='Account Number')),
                ('Description', models.CharField(max_length=150, verbose_name='Description')),
                ('Department', models.CharField(max_length=50, verbose_name='Department')),
                ('TypicalBal', models.CharField(max_length=5, verbose_name='Typical Balance')),
                ('DebitOffset', models.CharField(default=None, max_length=30, null=True)),
                ('CreditOffset', models.CharField(default=None, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
