# Generated by Django 4.1.1 on 2022-09-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='Account',
            field=models.CharField(max_length=10, verbose_name='Account Number'),
        ),
    ]
